### ISSUE TITLE
Q: why get rid of <keep-alive> ?

### ISSUE THREAD

**Issue by laur89** [johndatserakis/koa-vue-notes-web#10]
Hey man, glad to see you've updated the repos!
Sadly my fork has diverged quite a bit, but am trying to bring it up-to speed with your latest changes as much as possible.

Some questions have arisen while merging changes: why did you decide to get rid of the `<keep-alive>` wrapper around the router-view tag?

**Comment by johndatserakis** [comment]
Hey there - ha yea it needed a little bit of a touch-up - and plus, I wanted to add TypeScript support as I really like TypeScript as I'm getting into it.

Hmm yea, about the `keep-alive` option - good question. 

What happened was, in my case in this app and my other apps, I ended up running into issues with the content in my components falling out of line with the API. In most cases, that's fine. But, conceptually, I'm kinda veering towards forcing the frontend to be a little bit more quick and outspoken about getting new data, so by taking out the `keep-alive`, I am able to utilized the `mounted` lifecycle method in a reliable way. I'd rather leave the concept of caching to the `vuex` store when I need to use caching.

Although it's funny - I just read up on `keep-alive` to see if there's more I can learn about it, and I notice that there's a special lifecycle hook called `activated` that is basically `mounted` for `keep-alive` components! Ha - didn't know that. Although I think I'll still leave data caching to the store, and I'll use `keep-alive` in the future with a component that has no connection to the store at all. 

Hope that helps.
