### ISSUE TITLE
Login broken on refreshToken expiry

### ISSUE THREAD

**Issue by laur89** [johndatserakis/koa-vue-notes-web#11]
Hi John,

think logout should be forced from `axios-auth-interceptor.refreshAuthLogic()` when 401 is returned from the api, indicating expired refreshToken. Otherwise client needs to manually nuke their localStorage to be able to continue - without doing so the web client will forever try to refresh the access token that will never succeed.

**Comment by johndatserakis** [comment]
Hey there, yea I think that's a good point. 

I haven't looked at the code in a bit. I think the way I'm dealing with an invalid token now is to basically redirect the user to the home page and tell them to login again.

Agreed - it would be better to maybe delete the `localStorage` content at that point so as to prevent further calls with a token that has already been identified as invalid.

At some point I'm going to come back to this project to perhaps touch it up a bit. I'll look to institute this fix at that point. Thank you.

**Comment by laur89** [comment]
> I think the way I'm dealing with an invalid token now is to basically redirect the user to the home page and tell them to login again.

My fork may possibly have diverged too far, but can't find such a redirect logic. Can see logout is only handled by the [NavbarAccount.vue](https://github.com/johndatserakis/koa-vue-notes-web/blob/develop/src/components/partials/main/NavbarAccount.vue); am I missing something?

**Comment by johndatserakis** [comment]
Yea I think you're right - I believe what I mentioned was in the initial iteration of this project, but didn't make it in the revamp I did a few years back.

Thanks for pointing it out!
