### ISSUE TITLE
event of "confirmDeleteNote" not work

### ISSUE THREAD

**Issue by changzhiwin** [johndatserakis/koa-vue-notes-web#4]
I think https://github.com/johndatserakis/koa-vue-notes-web/blob/c16bf0d3a4e3859bb283e223bf5743df8fd6016a/src/components/Layouts/EditNote.vue#L20
should change to 
`<button @click="$root.$emit('confirmDeleteNote')" class="btn btn-danger">...`
is that right?

**Comment by johndatserakis** [comment]
Hey there @changzhiwin - thanks for checking out the project.

Good catch - soon I will update this part of the project - and I will remove parts of the [EditNote.vue](https://github.com/johndatserakis/koa-vue-notes-web/blob/master/src/components/Layouts/EditNote.vue) that use the `this.$root.$on / this.$root.$off` as that part isn't being used. Sorry I left that in there.

Right now the `confirmDeleteNote` method is not being used. What I'll do is have line 20 updated to the below:

```javascript
<button @click="confirmDeleteNote" class="btn btn-danger"><i class="fa fa-trash fa-fw"></i> Delete Note</button>
```

That way, when someone clicks delete - it will confirm the deletion before following through.

Thanks for pointing this out, and I'll update here when complete.

**Comment by changzhiwin** [comment]
Got. I use this project for learning, thanks for your reply and good work

**Comment by johndatserakis** [comment]
Ok cool - I've merged your pull request and updated the project further. Should be good for now. Thank you.
