### ISSUE TITLE
When token expired,

### ISSUE THREAD

**Issue by gokaybiz** [johndatserakis/koa-vue-notes-web#7]
Front pushing that alert message:
```
Server Error
Hmm, there was an error creating your account. Please try again.
```

and
`api/v1/user/refreshAccessToken`
returns `"INVALID_REFRESH_TOKEN"`

https://github.com/johndatserakis/koa-vue-notes-web/blob/87912aea2c0fe830c1ddbe520b15ad59ee773037/src/common/axios-auth-interceptor.ts#L18
May it should be logged user's username
`import { user } from "@/store/user";`
...
`username: user.getters["username"],`

**Comment by johndatserakis** [comment]
Great eye - thank you for pointing this out. I had to import the store in slightly a different way, but it's all set now. Thank toy. Fixed in https://github.com/johndatserakis/koa-vue-notes-web/pull/9.
